### ISSUE TITLE
__typename in fieldsList

### ISSUE THREAD

**Issue by ziimakc** [Mikhus/graphql-fields-list#11]
Can we exclude '__typename' from fieldsList?

```
const some = fieldsList(info)
// some output
[ 'id', 'name', '__typename' ]
```

**Comment by Mikhus** [comment]
Sure, you can use `skip` option:
~~~typescript
const some = fieldsList(info, { skip: ['__*'] })
~~~

**Comment by ziimakc** [comment]
@Mikhus should't fieldsList not contain __typename by default? Or this field added by apollo or other library?

**Comment by Mikhus** [comment]
This is Apollo specific problem
