### ISSUE TITLE
Update the readme to show the most basic usage first

### ISSUE THREAD

**Issue by Apollinaire** [Mikhus/graphql-fields-list#12]
Hi, 
First of all, thanks for creating and publishing the lib. 
Since the readme is the main documentation for it, you should update it a bit. 
Here is what I recommand: 
- Put the "Breaking changes" section lower. 
- Put the simplest usage example in the first position

For the following query :
```
{
  post { # post: [Post]
    id
    author: {
      id
      firstName
      lastName
    }
  }
}
```

```
resolve(source, args, context, info) { // resolver of Post.author, 
  console.log(fieldsList(info)); // ['id', 'firstName', 'lastName']
}
```

For a newcomer to the librairy, this was my use case. I spent ~30 minutes reading the whole readme with all the use cases just to wonder if I could find a way not to use the `path` option, to just get the first children fields. Finally, I gave up, installed the repo and tried myself the snippet above. I still don't know if it's safe btw, because it's not documented.

**Comment by Mikhus** [comment]
Hi, @Apollinaire !

Thanks for sharing your user experience and giving this valuable advice. I'm pretty sure your suggestion could make this library usage better and more comfortable for users, so I did as you've asked. Please, check, if it looks good at https://github.com/Mikhus/graphql-fields-list/blob/master/README.md#simplest-usage-examples

All kind regards,
Mike

**Comment by Apollinaire** [comment]
It's better this way, however now that I see it the `console.log` statements are bad for the readability.
I rephrased the line in the middle, and the second part is the resolver of `post` (the query) not `Post` (the type)

Here is my updated propostion

```js
resolve(source, args, context, info) { // resolver of Post.author, 
  fieldsList(info);       // [ 'id', 'firstName', 'lastName' ]
  fieldsMap(info);        // { id: false, firstName: false, lastName: false }
  fieldsProjection(info); // { id: 1, firstName: 1, lastName: 1 };
}

// or, if there is high-level resolver does the work:

resolve(source, args, context, info) { // resolver of post
  fieldsList(info);       // [ 'id', 'author' ]
  fieldsMap(info);        // { id: false, author: { id: false, firstName: false, lastName: false } }
  fieldsProjection(info); // { id: 1, 'author.id': 1, 'author.firstName': 1, 'author.lastName': 1 };
}
```

Finally, there was a typo in the graphql query I gave you : the colon after `author` should not be here, so it becomes:

```graphql
{
  post { # post: Post
    id
    author {
      id
      firstName
      lastName
    }
  }
}
```
I also changed `[Post]` to `Post` for simplicity
