### ISSUE TITLE
How to handle computed values?

### ISSUE THREAD

**Issue by brielov** [Mikhus/graphql-fields-list#13]
Suppose you have a `User` type that has firstName and lastName but the schema also has a fullName that concatenates the first two. If you don't request firstName and lastName, fullName would be null. How can I get around this?

```graphql
# schema.graphql
type User {
  firstName: String!
  lastName: String!
}
``` 

```javascript
// resolvers.js
{
  fullName: {
    resolve(parent) {
      return `${parent.firstName} ${parent.lastName}`
    }
  }
}
```

**Comment by Mikhus** [comment]
That is not in scope of what this library do. You need to define these kind of dependencies yourself. This library only provides you with information which fields was requested by the end user and nothing more. So, to resolve this you should do something like this:
~~~javascript
// we mean parent (user object) resolver here:
{
    async resolve(src, args, info) {
        const fields = fieldsList(info);

        if (fields.indexOf('fullName') !== -1) {
            // make sure we request dependency fields explicitly,
            // even if they don't requested by the end user
            if (fields.indexOf('firstName') === -1) {
                fields.push('firstName');
            }
            if (fields.indexOf('lastName') === -1) {
                fields.push('lastName');
            }
        }
        
        return await fetchEntity(args.id, fields);
    }
}
~~~

If you need to utilize other data structures, produced by `fieldsMap()` or `fieldsProjection()` adopt the code above to proper circumstances. I guess the general idea should be pretty clear.
