### ISSUE TITLE
Feature Request [fieldsProjection]

### ISSUE THREAD

**Issue by mohamedGamalAbuGalala** [Mikhus/graphql-fields-list#17]
Thanks for the library :heart: 
_______________________________________________

In this example `fieldsProjection` will result `{ id: 1, 'author.id': 1, 'author.firstName': 1, 'author.lastName': 1 }`

But I want to set an option like `fieldsProjection(info, { keepParentField: true })` to make it return this  `{ id: 1, 'author': 1, 'author.id': 1, 'author.firstName': 1, 'author.lastName': 1 }`

```
{
  post { # post: [Post]
    id
    author: {
      id
      firstName
      lastName
    }
  }
}

resolve(source, args, context, info) { // resolver of Post
  console.log(fieldsProjection(info)); // { id: 1, 'author.id': 1, 'author.firstName': 1, 'author.lastName': 1 };
}
```

This will be very helpful in case you have a document like this in DB
```

@ObjectType()
export default class Member implements IMember {
  @prop({ ref: User, required: true, index: true })
  User: Ref<User>

  @Field(() => TeamMemberRole)
  @prop({ type: String, required: true, default: TeamMemberRole.MEMBER })
  Role: TeamMemberRole

  @Field()
  @prop({
    required: true,
    default: () => new Date().getTime()
  })
  AddedOn: number
}

@ObjectType()
export default class Company extends BaseModel implements ICompany {
  @Field()
  @prop({ required: true })
  Name: string

  @Field(() => Member)
  @prop({ items: Member, _id: false, default: [] })
  Members: Member[]
}
```

And you have a field resolver on Member.User and you want to do a projection for this user, in the `Company` Resolver you will have `Member.User.ID` but not `Member.User` so in the `Member.User` resolver the User value will be null.
but if you had `Member.User.ID` **and `Member.User`** this will fix the problem.

For now, I do a workaround to get the result I want

```
   
    const projection = fieldsProjection(info)

    AppendBaseKeyWithRegixCheckForChilds(projection, 'Members.User')

_____________________________________________________
const AppendBaseKeyWithRegixCheckForChilds = (
  projection: {},
  baseKey: string
): void => {
  Object.keys(projection).forEach(k => {
    if (RegExp(`${baseKey}.`).test(k)) {
      delete projection[k]
      projection[baseKey] = 1
    }
  })
}


```
Maybe my use case is too personalized and I don't mind if it is.

Thanks again for your work :heart:

**Comment by Mikhus** [comment]
Seems legit, can you suggest PR for this? Currently I'm too busy to make this enhancement, so I can;t promise any quick implementation for this...

**Comment by mohamedGamalAbuGalala** [comment]
I had this issue on my notifications for 29 days till I decided to invest some time and create this pr, now I can mark it as done :heavy_check_mark:  :joy: :joy:
