### ISSUE TITLE
Why fieldsMap returns false ?

### ISSUE THREAD

**Issue by PacoDu** [Mikhus/graphql-fields-list#2]
Hello,
Why did you choose to return `false` instead of `true` for the `fieldsMap` function ? 

From the user POV it's a bit strange as we are looking for the fields requested by the query and they are mapped to a false value when, as a user of the library, I was intuitively expecting a `true` value.

**Comment by Mikhus** [comment]
Because when you traversing an object tree truthy value would meen there is a nesting branch, falsy value gives a sign you reached a branch end...

**Comment by PacoDu** [comment]
I understand, but I was speaking from a user point of view. Isn't the goal of this library to retrieve the selected field ? In this case the user would expect a truthy value, not the bare result of the algorithm.

A simple use case: if this map was returning true we coud directly inject the leaf object in a mongodb projection without having to revert the resulting map. 

Anyway that was just for curiosity, I understand why you chose false now (for complex nested objects), Thanks!

**Comment by Mikhus** [comment]
Mongodb projection is a specific usage, where you would need to rebuild an object structure to dot notation for general use case. I can suggest such kind of behavior could be possible to implement in this library as a specific function, like fieldsProjection, or you can suggest a PR for that :)

**Comment by Mikhus** [comment]
@PacoDu, `fieldsProjection()` support added in v2.0.0, please, refer documentation in README.md file...
