### ISSUE TITLE
Exclude __typename in root and all nested

### ISSUE THREAD

**Issue by Akxe** [Mikhus/graphql-fields-list#26]
Hi, I would like to be able to remove `__typename` from the whole tree. I thought something like `*.__typename` might work, but it did not :/

**Comment by dallenbaldwin** [comment]
In the latest version I was able to use `skip: ['*.__*']` to exclude all `__typename` fields

**Comment by Mikhus** [comment]
Workaround described by @dallenbaldwin is absolutely correct way to do that
