### ISSUE TITLE
Decommissioned @types/graphql is being used by this package

### ISSUE THREAD

**Issue by mcrawshaw** [Mikhus/graphql-fields-list#33]
The graphql package now includes types. This can cause the following error:
```node_modules/graphql-fields-list/index.ts:21:5 - error TS2614: Module '"graphql"' has no exported member 'SelectionNode'. Did you mean to use 'import SelectionNode from "graphql"' instead```

Just a matter of updating `index.ts` from:
```
import {
    ArgumentNode,
    DirectiveNode,
    SelectionNode,
    FragmentDefinitionNode,
    GraphQLResolveInfo,
    FieldNode,
} from 'graphql';
```
to
```
import {
    GraphQLResolveInfo,
} from 'graphql/type';
import {
    ArgumentNode,
    DirectiveNode,
    SelectionNode,
    FragmentDefinitionNode,
    FieldNode,
} from 'graphql/language';
```

**Comment by Mikhus** [comment]
should be fine since 2.3.x
